baseURL: "https://victorchen-github.github.io/my-website/" 
title: Victor Chen
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "This website hosts Victor Chen's research papers, Teaching portfolio, course materials, curriculum vitae, and contact information."
    author: Victor(Zhengyifan) Chen
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Victor(Zhengyifan) Chen
          subtitle: "Welcome! I’m Victor Chen, a PhD candidate in Finance at the I.H. Asper School of Business, University of Manitoba. \n\n 
                     <br>
                     **My research** focuses on information efficiency in financial markets, with particular interest in how social context and investor ability shape asset prices. I use large-scale datasets, network analysis, and structural modeling to study questions around racial integration, mutual fund performance, and information diffusion. \n\n
                     <br>
                     This website shares my research, teaching portoflio, and CV. Please feel free to reach out if you'd like to collaborate, chat about ideas, or just connect over shared interests."
          imageUrl: "self-pic.JPG"
          imageWidth: 230
          imageHeight: 230
          buttons:
            - name: Working Papers
              url: papers/
            - name: Publications
              url: data/
     #       - name: Books
     #         url: books/
            - name: Teaching
              url: courses/
     #       - name: Tags
     #         url: tags/
     #       - name: Archive
     #         url: archive/
            - name: CV
              url: cv.pdf

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:Zhengyifan.chen@ubc.ca
   #     - name: Zoom
   #       url: https://www.zoom.us/my/igelfeld
        - name: Location
          url: location/
   #    - name: Office Hours
   #      url: officehours/
        - name: Google Scholar
          url: https://scholar.google.ca/citations?user=dNRi3IIAAAAJ&hl=en&oi=sra
    #    - name: GitHub
    #      url: https://github.com/pmichaillat
    #    - name: Substack
    #      url: https://pmichaillat.substack.com
    #    - name: YouTube
    #      url: https://www.youtube.com/@pmichaillat
        - name: LinkedIn
          url: https://www.linkedin.com/in/victor-chen-5b13a21b7/
    #    - name: Bluesky
    #      url: https://bsky.app/profile/pmichaillat.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Victor (Zhengyifan) Chen"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2